
services:
  # Backend Service
  backend:
    build:
      context: ./backend # Path to the directory containing the backend Dockerfile
      dockerfile: Dockerfile
    container_name: bluEOView_backend
    ports:
      - "5000:5000" # Map host port 5000 to container port 5000
    environment:
      - API_PORT=5000

  # Frontend Service
  frontend:
    build:
      context: ./frontend # Path to the directory containing the frontend Dockerfile
      dockerfile: Dockerfile
    container_name: bluEOView_frontend
    ports:
      - "8080:80" # Map host port 8080 to container Nginx port 80
    depends_on:
      - backend # Ensures backend starts before the frontend (good practice)
